# Generated by Django 3.1.1 on 2020-09-19 09:53

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200919_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=polls.models.now_plus_30),
        ),
    ]
